import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { formatDate } from "@/lib/funding";
import { ArrowRight, CalendarDays, FolderKanban, Loader2, Plus } from "lucide-react";
import { Link } from "wouter";

const statuses = ["Draft", "In Progress", "Submitted", "Awarded", "Rejected"] as const;
const statusTone: Record<(typeof statuses)[number], string> = { Draft: "bg-stone-100 text-stone-700", "In Progress": "bg-sky-50 text-sky-800", Submitted: "bg-violet-50 text-violet-800", Awarded: "bg-emerald-50 text-emerald-800", Rejected: "bg-rose-50 text-rose-800" };

export default function Applications() {
  const { data, isLoading } = trpc.applications.list.useQuery();
  if (isLoading) return <DashboardLayout><div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#48786a]" /></div></DashboardLayout>;
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#6b887d]">Application workspace</p><h1 className="mt-2 font-display text-4xl tracking-[-0.04em] text-[#17443c]">From intent to submission.</h1><p className="mt-2 text-sm leading-6 text-[#677a72]">Create a structured workspace for each opportunity and keep the required work visible.</p></div><Button asChild className="rounded-full bg-[#0f3d36] text-white"><Link href="/funding"><Plus className="mr-2 h-4 w-4" />Create from opportunity</Link></Button></div>{data?.length ? <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(({ application, opportunity }) => <Link href={`/applications/${application.id}`} key={application.id} className="group rounded-2xl border border-[#dbe6df] bg-white p-5 shadow-[0_8px_25px_rgba(20,61,51,0.04)] transition hover:-translate-y-0.5 hover:border-[#a9c4b6] hover:shadow-[0_14px_38px_rgba(20,61,51,0.08)]"><div className="flex items-start justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold uppercase tracking-[0.1em] ${statusTone[application.status]}`}>{application.status}</span><ArrowRight className="h-4 w-4 text-[#6b877d] transition-transform group-hover:translate-x-0.5" /></div><h2 className="mt-5 font-display text-2xl leading-tight text-[#1b493f]">{application.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#6a7c74]">{opportunity.title}</p><div className="mt-5 border-t border-[#e5ece7] pt-4"><p className="flex items-center gap-2 text-xs font-semibold text-[#5d766d]"><CalendarDays className="h-3.5 w-3.5" />{application.targetDeadlineAt ? `Deadline ${formatDate(application.targetDeadlineAt)}` : "Deadline to be confirmed"}</p></div></Link>)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-[#bdcec5] bg-[#f7faf7] p-12 text-center"><FolderKanban className="mx-auto h-7 w-7 text-[#729186]" /><h2 className="mt-4 font-display text-3xl text-[#1e4b40]">Your workspace is ready when you are.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#6b7e76]">Start with an opportunity in the catalogue. Creating an application adds a focused workspace with the required status lifecycle and document checklist.</p><Button asChild className="mt-6 rounded-full bg-[#0f3d36] text-white"><Link href="/funding">Explore funding</Link></Button></div>}</div></DashboardLayout>;
}
